# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  jmap-serverless

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Parameters section
Parameters:
  RootDomainName:
    Type: String
    Description: Root domain name for the JMAP API
  AdminUsername:
    Type: String
    Description: Admin username (without domain, will be used as username@RootDomainName)
    Default: admin

# Globals section for shared function and API Gateway configuration
Globals:
  Function:
    Runtime: nodejs22.x
    Architectures:
      - arm64
    Timeout: 30

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Explicit API Gateway with Cognito authorization
  JmapApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn
        AddDefaultAuthorizerToCorsPreflight: false
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  # Cognito User Pool Domain (required for hosted UI)
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub '${AWS::StackName}-auth'
      UserPoolId: !Ref UserPool

  # Cognito User Pool Client (required for API Gateway integration)
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: jmap-serverless-client
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      CallbackURLs:
        - !Sub 'https://${RootDomainName}'
        - !Sub 'https://${RootDomainName}/'
        - !Sub 'https://jmap.${RootDomainName}'
        - !Sub 'https://jmap.${RootDomainName}/'
      LogoutURLs:
        - !Sub 'https://${RootDomainName}'
        - !Sub 'https://jmap.${RootDomainName}'
      SupportedIdentityProviders:
        - COGNITO

  # Admin user for the User Pool
  AdminUser:
    Type: AWS::Cognito::UserPoolUser
    DependsOn: UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      Username: !Sub '${AdminUsername}@${RootDomainName}'
      MessageAction: SUPPRESS
      UserAttributes:
        - Name: email
          Value: !Sub '${AdminUsername}@${RootDomainName}'
        - Name: email_verified
          Value: 'true'
      DesiredDeliveryMediums: []
      ForceAliasCreation: false

  # Lambda function: JMAP well-known endpoint handler
  wellKnownJmapFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/well-known-jmap.wellKnownJmapHandler
      Environment:
        Variables:
          API_URL: !Sub 'https://jmap.${RootDomainName}/'
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref JmapApi
            Path: /.well-known/jmap
            Method: GET
            Auth:
              Authorizer: NONE
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        External:
          - '@aws-sdk/*'
        EntryPoints:
          - src/handlers/well-known-jmap.ts

  # Lambda function: Auth test (requires Cognito auth)
  authTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/auth-test.authTestHandler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref JmapApi
            Path: /auth-test
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        External:
          - '@aws-sdk/*'
        EntryPoints:
          - src/handlers/auth-test.ts

  

  # User pool for auth (cognito)
  UserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Retain
    Properties:
      UserPoolName: jmap-serverless-UserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true

      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false



Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${JmapApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
  RestApiId:
    Description: "API Gateway Rest API ID"
    Value: !Ref JmapApi
  RestApiStageName:
    Description: "API Gateway stage name"
    Value: Prod
  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref UserPool
  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref UserPoolClient
  CognitoHostedUIUrl:
    Description: "Cognito Hosted UI URL for login"
    Value: !Sub "https://${AWS::StackName}-auth.auth.${AWS::Region}.amazoncognito.com/login?client_id=${UserPoolClient}&response_type=code&redirect_uri=https://${RootDomainName}"
  CognitoHostedUIDomain:
    Description: "Cognito Hosted UI Domain"
    Value: !Sub "${AWS::StackName}-auth.auth.${AWS::Region}.amazoncognito.com"
